# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pianoRoll.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(416, 349)
        MainWindow.setAutoFillBackground(False)
        self.note_n0 = QtWidgets.QToolButton(MainWindow)
        self.note_n0.setGeometry(QtCore.QRect(70, 50, 41, 161))
        self.note_n0.setAutoFillBackground(False)
        self.note_n0.setText("")
        self.note_n0.setCheckable(True)
        self.note_n0.setObjectName("note_n0")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.note_n0)
        self.note_n2 = QtWidgets.QToolButton(MainWindow)
        self.note_n2.setEnabled(True)
        self.note_n2.setGeometry(QtCore.QRect(110, 50, 41, 161))
        self.note_n2.setAutoFillBackground(False)
        self.note_n2.setText("")
        self.note_n2.setCheckable(True)
        self.note_n2.setObjectName("note_n2")
        self.buttonGroup.addButton(self.note_n2)
        self.note_n4 = QtWidgets.QToolButton(MainWindow)
        self.note_n4.setGeometry(QtCore.QRect(150, 50, 41, 161))
        self.note_n4.setAutoFillBackground(False)
        self.note_n4.setText("")
        self.note_n4.setCheckable(True)
        self.note_n4.setObjectName("note_n4")
        self.buttonGroup.addButton(self.note_n4)
        self.note_n5 = QtWidgets.QToolButton(MainWindow)
        self.note_n5.setGeometry(QtCore.QRect(190, 50, 41, 161))
        self.note_n5.setAutoFillBackground(False)
        self.note_n5.setText("")
        self.note_n5.setCheckable(True)
        self.note_n5.setObjectName("note_n5")
        self.buttonGroup.addButton(self.note_n5)
        self.note_n7 = QtWidgets.QToolButton(MainWindow)
        self.note_n7.setGeometry(QtCore.QRect(230, 50, 41, 161))
        self.note_n7.setAutoFillBackground(False)
        self.note_n7.setText("")
        self.note_n7.setCheckable(True)
        self.note_n7.setObjectName("note_n7")
        self.buttonGroup.addButton(self.note_n7)
        self.note_n9 = QtWidgets.QToolButton(MainWindow)
        self.note_n9.setGeometry(QtCore.QRect(270, 50, 41, 161))
        self.note_n9.setAutoFillBackground(False)
        self.note_n9.setText("")
        self.note_n9.setCheckable(True)
        self.note_n9.setObjectName("note_n9")
        self.buttonGroup.addButton(self.note_n9)
        self.note_n11 = QtWidgets.QToolButton(MainWindow)
        self.note_n11.setGeometry(QtCore.QRect(310, 50, 41, 161))
        self.note_n11.setAutoFillBackground(False)
        self.note_n11.setText("")
        self.note_n11.setCheckable(True)
        self.note_n11.setObjectName("note_n11")
        self.buttonGroup.addButton(self.note_n11)
        self.note_n1 = QtWidgets.QToolButton(MainWindow)
        self.note_n1.setGeometry(QtCore.QRect(100, 50, 21, 101))
        self.note_n1.setAutoFillBackground(False)
        self.note_n1.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.note_n1.setText("")
        self.note_n1.setCheckable(True)
        self.note_n1.setObjectName("note_n1")
        self.buttonGroup.addButton(self.note_n1)
        self.note_n3 = QtWidgets.QToolButton(MainWindow)
        self.note_n3.setGeometry(QtCore.QRect(140, 50, 21, 101))
        self.note_n3.setAutoFillBackground(False)
        self.note_n3.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.note_n3.setText("")
        self.note_n3.setCheckable(True)
        self.note_n3.setObjectName("note_n3")
        self.buttonGroup.addButton(self.note_n3)
        self.note_n6 = QtWidgets.QToolButton(MainWindow)
        self.note_n6.setGeometry(QtCore.QRect(220, 50, 21, 101))
        self.note_n6.setAutoFillBackground(False)
        self.note_n6.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.note_n6.setText("")
        self.note_n6.setCheckable(True)
        self.note_n6.setObjectName("note_n6")
        self.buttonGroup.addButton(self.note_n6)
        self.note_n8 = QtWidgets.QToolButton(MainWindow)
        self.note_n8.setGeometry(QtCore.QRect(260, 50, 21, 101))
        self.note_n8.setAutoFillBackground(False)
        self.note_n8.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.note_n8.setText("")
        self.note_n8.setCheckable(True)
        self.note_n8.setObjectName("note_n8")
        self.buttonGroup.addButton(self.note_n8)
        self.note_n10 = QtWidgets.QToolButton(MainWindow)
        self.note_n10.setGeometry(QtCore.QRect(300, 50, 21, 101))
        self.note_n10.setTabletTracking(True)
        self.note_n10.setAutoFillBackground(False)
        self.note_n10.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.note_n10.setText("")
        self.note_n10.setCheckable(True)
        self.note_n10.setObjectName("note_n10")
        self.buttonGroup.addButton(self.note_n10)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(100, 20, 221, 16))
        self.label.setObjectName("label")
        self.identify_chord = QtWidgets.QPushButton(MainWindow)
        self.identify_chord.setGeometry(QtCore.QRect(60, 230, 114, 32))
        self.identify_chord.setObjectName("identify_chord")
        self.exit_button = QtWidgets.QPushButton(MainWindow)
        self.exit_button.setGeometry(QtCore.QRect(60, 290, 114, 32))
        self.exit_button.setObjectName("exit_button")
        self.label_2 = QtWidgets.QLabel(MainWindow)
        self.label_2.setGeometry(QtCore.QRect(250, 230, 121, 71))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.clear_button = QtWidgets.QPushButton(MainWindow)
        self.clear_button.setGeometry(QtCore.QRect(60, 260, 114, 32))
        self.clear_button.setObjectName("clear_button")
        self.note_n7.raise_()
        self.note_n9.raise_()
        self.note_n2.raise_()
        self.note_n11.raise_()
        self.note_n5.raise_()
        self.note_n4.raise_()
        self.note_n0.raise_()
        self.note_n1.raise_()
        self.note_n3.raise_()
        self.note_n6.raise_()
        self.note_n8.raise_()
        self.note_n10.raise_()
        self.label.raise_()
        self.identify_chord.raise_()
        self.exit_button.raise_()
        self.label_2.raise_()
        self.clear_button.raise_()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chord Identifier"))
        self.label.setText(_translate("MainWindow", "Pick some notes to identify a chord"))
        self.identify_chord.setText(_translate("MainWindow", "Chord"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Chord:</p><p><br/></p></body></html>"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))

